apiVersion: v1
kind: Pod
metadata:
  name: db-locked
spec:
  containers:
  - image: mysql:8-debian
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret #ref to the secret
          key: password #ref to the key in the secret