apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod-counter
spec:
  containers:
  - name: counter-1
    image: busybox
    args: ["sh", "-c", "while true; do echo Hello from counter-1; sleep 5; done"]
  - name: counter-2
    image: busybox
    args: ["sh", "-c", "while true; do echo Hello from counter-2; sleep 5; done"]